---
title: "Take-home Exercise 4"
description: "Putting Visual Analytics into Practical Use"
date: "4 February 2023"
date-modified: "`r Sys.Date()`"
format: html
editor: visual
---

## The Task

In this take-home exercise, you are required to uncover the impact of COVID-19 as well as the global economic and political dynamic in 2022 on Singapore bi-lateral trade (i.e. Import, Export and Trade Balance) by using appropriate analytical visualisation techniques learned in **Lesson 6: It's About Time**. Students are encouraged to apply appropriate interactive techniques to enhance user and data discovery experiences.

## The Data

For the purpose of this take-home exercise, Merchandise Trade provided by Department of Statistics, Singapore (DOS) will be used. The data are available under the sub-section of Merchandise Trade by Region/Market. You should download the data by clicking on the link **Download all in Excel** on the same webpage. The study period should be between **January 2020 to December 2022**.

## The Designing Tool

For the purpose of this take-home exercise, ggplot2 and its extension should be used to design the analytical visualisation. tidyverse family of packages should be used to prepare the data.

## The Write-up

The write-up of the take-home exercise should include but not limited to the followings:

-   Describe the selection and designed consideration of the analytical data visualisation used. The discussion should limit to not more than 150 words each.

-   A reproducible description of the procedures used to prepare the analytical visualisation. Please refer to the peer submission I shared.

-   A write-up of not more than 100 words to discuss the patterns reveal by each analytical visualisation prepared.

## Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

The specific submission instructions are as follows:

-   The analytical visualisation must be prepared by using **R and appropriate R packages**.
-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
-   Provide the links to the Take-home Exercise write-up and github repository onto eLearn (i.e. Take-home Exercise section)

## Submission date

The completed take-home exercise is due on **26th February 2023, by 11:59pm evening**.

## Learning from senior

-   KELLY KOH KIA WOON DataViz Makeover write-up on [Netlify](https://kellykkw.netlify.app/posts/2021-05-15-dataviz-makeover-1/) and [Tableau Public link](https://public.tableau.com/app/profile/kelly2850/viz/DatavizMakeover1_16220368938730/Dashboard1). A must read submission.

-   [How has Singapore changed since 2011?](https://rpubs.com/raymondteo/dataviz8) by Raymond TEO LIP PENG. This submission provides an useful reference on how to create animated motion plot by using time-oriented data.

-   [Singapore's Demographic Composition Across Time](https://rpubs.com/deniseadele/584423) by DENISE ADELE CHUA HUI SHAN. This submission provides interesting approaches to reveal values change over time without having to use animation.

# Peer Learning

-   [AISHWARYA SANJAY MALOO](https://isss608-ay-2022-23-aishwaryamaloo.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [ANICA CLARICE ANTONELLA PASCUAL GALANO](https://acapvisualano.netlify.app/take-home_ex/take-home_ex4/take-home_ex4)
-   [ARIANA TAN RUI MIN](https://arianatan-jan23isss608.netlify.app/takehome_ex/takehome_ex_04/takehome_ex_04)
-   [BHAIRAVI VAIRAVELU](https://isss608-ay2022-23t2-vb.netlify.app/take_home_ex/take_home_ex04/take_home_ex04)
-   [BRYANT PHILIPPE LEE](https://isss608-2023-bsl.netlify.app/take-home_ex/take-home_ex04)
-   [CHAN JING WEI MAGDALENE](https://magdalenechan-iss608.netlify.app/take_home_ex/take_home_ex04/take_home_ex04)
-   [CHANG XIN XIN EDA](https://isss608-edachang.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [CHEN YIMAN](https://yimanchen-isss608.netlify.app/takehome/takehome04/takehome04)
-   [CHERYL JEANNE CHIEW](https://cheryljeanne-isss608-ay2223.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [CHOI SUNHAM](https://aashleychoii.netlify.app/take-home-exercise/take-home-exercise_04)
-   [FARRAH BINTE MOHD FADIL](https://farrahmf.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [HOANG HUY](https://isss608-thomashoang.netlify.app/takehomeex/takehomeex04)
-   [HOU TAO](https://isss608-vaa-ht.netlify.app/takehome_ex/takehome_ex04/takehome_ex04)
-   [HUO DA](https://isss608-ay2022-23-huoda.netlify.app/take-home_ex/take-home_ex04/take_home_ex04)
-   [KHOO WEI LUN](https://isss608-khooweilun.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [LAU ZHI YONG WILLIE](https://isss608-willielau.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [LAW MAN LONG](https://mllaw-isss608-ay21-22jan.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [LAW SHIANG ROU](https://isss608-shiangrou.netlify.app/take_home_exercise/take_home_exercise_4/take_home_exercise_4)
-   [LI XINGYUN](https://zesty-stroopwafel-336561.netlify.app/takehomeexercises/takehomeex4/takehomeex4)
-   [LI YIXUAN](https://isss608-daisy.netlify.app/take-home-ex/take-home-4/take-home-4.html)
-   [LI ZIYI](https://visual-analytics-applications-lzy.netlify.app/take-home_ex/ex04/take-home_ex04)
-   [LIANG MINGHAO](https://isss608-2023-minghao.netlify.app/takehome_4/takehome_4.html)
-   [LIM EN HUI CHRISTIANA](https://visualanalytics-christianalim-jan2023.netlify.app/take%20home%20exercises/take-home-exercise-4)
-   [LUO ZHENG](https://zoeluvrisss608.netlify.app/take-home_ex/take-home_ex04/take-home_ex04_draft)
-   [MICHAEL KEVIN WIRATAMA DJOHAN](https://isss608-michaeldj.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [PRACHI RAJENDRA ASHANI](https://isss608-ay2022-23-prachi.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [SHI CHEE LIANG](https://isss608scl.netlify.app/takehomeex/takehomeex04/takehomeex04)
-   [SIDDHARTH SINGH](https://siddharthsingh-isss608-ay2022-23t1.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [SRIVATSAN MADAPUZI SRINIVASAN](https://vaa-mssri-2022-23.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [TAN ZEXEONG](https://visual-analytics-jephostan.netlify.app/takehome/th_ex4/th_ex4)
-   [TAN ZHI HAO](https://isss608-ay2022-23t2-tanzhihao.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [TAO MEIZHU](https://isss608-vaa-meizhu.netlify.app/take-home%20exercise/take-home%20exercise%204/take-home%20exercise%204)
-   [TASAPORN VISAWAMETEEKUL](https://isss608-tasapornv.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [WANG KUNRUI](https://olivia-vaa-smu.netlify.app/kunruiwang-takehome4)
-   [WANG RUIPENG](https://isss608-rp.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [XU JIAJIE](https://isss608-ay2022-23t1.netlify.app/take-home_ex/takehome_ex04/takehome_ex04#the-task)
-   [YIN HANG](https://isss608-ay2022-23t2.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [YUN SHWE YEE KYAW](https://isss608-vaa-2022.netlify.app/take-home_ex/take-home_ex04/take-home_ex04)
-   [ZHU FANGYUAN](https://608vaa.netlify.app/take-home_ex4/take-home_ex4)
