---
title: "Take-home Exercise 1"
description: |
  Creating data visualisation beyond default
date: "`r Sys.Date()`"
format: html
editor: visual
---

Creating data visualisation beyond default

# The Task

[Age-sex pyramid](https://isss608-ay2022-23jan.netlify.app/outline/lesson01_outline#age-sex-pyramid) is an analytical visualisation commonly used by demographers to reveal the structure of population by gender and age group. In this take-home exercise, you are required to reveal the demographic structure of Singapore at planning area level by using age-sex pyramid method. Instead of plotting a single age-sex pyramid, however, you are required to display nine selected planning areas on a single view by using [trellis display (also know as small-multiple plot)](https://isss608-ay2022-23jan.netlify.app/outline/lesson01_outline#trellis-display).

# The Designing Tool

For the purpose of this take-home exercise, Tableau desktop should be used to design the analytical visualisation.

# The Data

*Singapore Residents by Planning Area / Subzone, Age Group, Sex and Type of Dwelling, June 2022* should be used to prepare the analytical visualisation. It is available at [Department of Statistics, Singapore](https://www.singstat.gov.sg/)(in short SingStat).

# The Write-up

The write-up of the take-home exercise should include but not limited to the followings:

-   A reproducible description of the procedures used to prepare the analytical visualisation. Please refer to the senior submission I shared for example [1](https://bilian-mitb2021.netlify.app/th_ex/dataviz2/dataviz2#step-by-step-description) and [2](https://isss608visualanalyticssun.netlify.app/dataviz/dataviz1/dataviz1#step-by-step-preparation).

-   A write-up of not more than 500 words to discuss the patterns reveal by the analytical visualisation prepared.

# Submission Instructions

This is an individual assignment. You are required to work on the take-home exercises and prepare submission individually.

The specific submission instructions are as follows:

-   The analytical visualisation must be prepared by using **Tableau Desktop**. The final workbook must be uploaded onto [Tableau Public](https://public.tableau.com/en-us/s/).
-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
-   Provide the links to the Take-home Exercise write-up, github repository and Tableau Public onto eLearn (i.e. Take-home Exercise section)

# Submission date

Your completed take-home exercise is due on **22nd January 2023, by 11:59pm evening**.

# Peer Learning

-   [AISHWARYA SANJAY MALOO](https://public.tableau.com/app/profile/aishwarya.maloo7070/viz/Take-Home_Ex01/Dashboard1?publish=yes)
-   [ANICA CLARICE ANTONELLA PASCUAL GALANO]()
-   [ARIANA TAN RUI MIN](https://public.tableau.com/app/profile/ariana.tan6501/viz/VATakeHome1/Sheet13)
-   [BHAIRAVI VAIRAVELU](https://public.tableau.com/app/profile/bhairavi.vairavelu/viz/Take_Home_Exercise_01/Top9PlanningAreasDashboard)
-   [BRYANT PHILIPPE LEE](https://public.tableau.com/views/DataVizMakeover01_16743910439700/TotalSingapore?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link)
-   [CHAN JING WEI MAGDALENE](https://public.tableau.com/app/profile/magdalene.chan/viz/TakeHome_Ex01/Dashboard1)
-   [CHANG XIN XIN EDA](https://public.tableau.com/views/PopulationPyramidSingaporeJun2022/SingaporesPopulationPyramid?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link)
-   [CHEN YIMAN](https://public.tableau.com/app/profile/yiman.chen/viz/takehome_ex01/Story1)
-   [CHERYL JEANNE CHIEW](https://public.tableau.com/app/profile/cheryl.jeanne/viz/Take-homeExercise1-Age-SexPyramid-TrellisDisplay/MatrixDashboard?publish=yes)
-   [CHOI SUNHAM](https://public.tableau.com/app/profile/ashley1342/viz/TakeHomeExercise01/Dashboard1?publish=yes)
-   [FARRAH BINTE MOHD FADIL](https://public.tableau.com/app/profile/farrahmf/viz/Take-home_Ex01/Age-SexPyramids1?publish=yes)
-   [HOANG HUY](https://public.tableau.com/app/profile/thomas.hoang8154/viz/takehome1_16740523080150/Dashboard3)
-   [HOU TAO](https://public.tableau.com/app/profile/jerry.hou/viz/Takehome_Ex01/SG2022PopulationbyAgeGroup_1?publish=yes)
-   [HUO DA](https://public.tableau.com/app/profile/huoda1027/viz/TakeHome_Ex01_16742612602400/Dashboard1?publish=yes)
-   [KHOO WEI LUN](https://public.tableau.com/app/profile/khoo.wei.lun/viz/SingaporePopulationPyramidsJune2022/DashboardTrellis)
-   [LAU ZHI YONG WILLIE](https://public.tableau.com/views/Take-home_Ex01_16743298500000/Dashboard1?:language=en-GB&publish=yes&:display_count=n&:origin=viz_share_link)
-   [LAW MAN LONG](https://public.tableau.com/app/profile/law.man.long/viz/Take-home_Ex1/SingaporePopulationPyramid)
-   [LAW SHIANG ROU](https://public.tableau.com/views/TakeHomeExercise1-20Jan2023/Dashboard1?:language=en-US&:display_count=n&:origin=viz_share_link)
-   [LI XINGYUN](https://public.tableau.com/app/profile/xingyunli/viz/takehomeexercise1/DemographicStructureofSingaporebyRegiontop9regionsinpopulation?publish=yes)
-   [LI YIXUAN](https://public.tableau.com/app/profile/yixuan.li1277/viz/take-home-1/Dashboard1)
-   [LI ZIYI](https://public.tableau.com/views/Take-home_Ex01_Dashboard/Dashboard?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link)
-   [LIANG MINGHAO](https://public.tableau.com/app/profile/minghao.liang/viz/take-home-1_16741369553030/AgePyramid?publish=yes)
-   [LIM EN HUI CHRISTIANA](https://public.tableau.com/app/profile/christiana.lim/viz/TakeHomeExercise1_16742278926320/Dashboard1?publish=yes)
-   [LUO ZHENG](https://public.tableau.com/app/profile/luo.zheng/viz/Take-home_Ex01edited/Dashboard1)
-   [MICHAEL KEVIN WIRATAMA DJOHAN](https://public.tableau.com/views/TakeHomeExercise01_16742904659610/SingaporePopulationPyramidbyPlanningAreaJune2022?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link)
-   [PRACHI RAJENDRA ASHANI](https://public.tableau.com/views/TakeHome_01/DBAge-SexPyramidbyPA?:language=en-US&:display_count=n&:origin=viz_share_link)
-   [SHI CHEE LIANG](https://public.tableau.com/app/profile/shi.chee.liang/viz/TakeHomeEx01_2/Dashboard1?publish=yes)
-   [SIDDHARTH SINGH](https://public.tableau.com/app/profile/siddharth.singh6175/viz/SiddharthSinghTakeHomeEx01/Age-SexPyramidforSingaporePlanningArea?publish=yes)
-   [SRIVATSAN MADAPUZI SRINIVASAN](https://public.tableau.com/app/profile/srivatsan.madapuzi.srinivasan/viz/Take-Home_Ex01_16743904663190/Dashboard1?publish=yes)
-   [TAN ZEXEONG](https://public.tableau.com/app/profile/joseph.zexeong.tan/viz/SingaporePopulationPyramindJun2022v1_3/trel3x3_d?publish=yes)
-   [TAN ZHI HAO](https://public.tableau.com/app/profile/tan.zh4404/viz/Take-home_Ex01_TanZhiHao/Age-SexPyramidforSelectedPlanningAreasinSingapore2022V2)
-   [TAO MEIZHU](https://public.tableau.com/app/profile/meizhu6437/viz/Take-homeExercise1_16743934867140/Dashboard1?publish=yes)
-   [TASAPORN VISAWAMETEEKUL](https://public.tableau.com/views/Take-home_01_PopulationbyPlanningArea/3x3Trellis?:language=en-US&:display_count=n&:origin=viz_share_link)
-   [WANG KUNRUI](https://public.tableau.com/app/profile/ruipeng.wang/viz/take_home_01/Dashboard1)
-   [WANG RUIPENG](https://public.tableau.com/app/profile/ruipeng.wang/viz/take_home_01/Dashboard1)
-   [XU JIAJIE](https://public.tableau.com/views/TakeHomeExercise01_16744007430230/PyramidofPlaningareas?:language=zh-CN&publish=yes&:display_count=n&:origin=viz_share_link)
-   [YIN HANG](https://public.tableau.com/views/TakehomeEx1/PopulationPyramidof9MostPopulatedPlanningAreasinSingaporein2022?:language=en-GB&:display_count=n&:origin=viz_share_link)
-   [YUN SHWE YEE KYAW](https://public.tableau.com/app/profile/yun.shwe.yee.kyaw/viz/Take-home_Ex01_16742356941600/Age-SexPyramid)
-   [ZHU FANGYUAN](https://public.tableau.com/app/profile/fangyuan.zhu/viz/Take-home_Ex1_16742470631170/A-Spyramid?publish=yes)
